### ISSUE TITLE
import without package namespace not working

### ISSUE THREAD

**Issue by guozheng** [estan/protoc-gen-doc#22] opened 2016-03-29 17:20 UTC
I have a setup like this:

proto files are stored in `src/main/foo/bar/User.proto` and  `src/main/foo/bar/Name.proto`

```
//User.proto
import "Name.proto";
package foo.bar;
option java_package = "foo.bar";
option java_outer_classname = "UserProtos";
message User {
  ...
}

//Name.proto
package foo.bar;
option java_package = "foo.bar";
option java_outer_classname = "NameProtos";
message Name {
  ...
}
```

then, when I compile proto, I use this and it compiled fine.

```
protoc --java_out=src/main/java \
-Isrc/main/foo/bar/ \
src/main/foo/bar/User.proto \
src/main/foo/bar/Name.proto
```

When I use proto-gen-doc on this setup, it gives error about not able to find proto files to import. I tried `src/main/foo/bar/` option to specify import search path, but `protoc-gen-doc` does not seem to support that option.

**Comment by estan** [comment] 2016-03-29 21:06
Thanks for reporting. This is a real bug introduced by me when I fixed #9. I'll try to fix it, but there are some difficulties actually (see my post at https://groups.google.com/forum/#!topic/protobuf/KxbvItIKz1k ).

In short, the problem is that the plugin needs to open some of the input files on its own (instead of letting the plugin framework do the parsing), to do some custom parsing of comments at the top of the file, but the plugin API seems to not support getting the full path, so I wrongly used just the file name. But this breaks in your case it seems. I'll see what the protobuf library authors has to say, perhaps there's some way I haven't found yet.

**Comment by estan** [comment] 2016-03-29 21:17
As a workaround for now, and assuming this is your only input directory, you can do:

```
cd src/main/foo/bar
protoc --doc_out=html,index.html:where/you/want/the/doc User.proto Name.proto
```

That is, run the compiler from the directory where you have your source files. Won't work if you have inputs in e.g. `src/main/foo/baz` as well though, in which case you'll just have to wait until it's fixed :/

**Comment by guozheng** [comment] 2016-03-30 16:44
thanks a lot, estan, the workaround works for me ;-)

BTW, may I make two more suggestions:
  1. the OUT_FILENAME or OUT_FILEPATH does not seem to support `~`, absolute path worked for me
  1. would it be possible to support glob for proto files, i.e. `*.proto`, it is a bit inconvenient to specifically type all the proto filenames

**Comment by estan** [comment] 2016-03-30 17:09
Tilde (`~`) and filename (`*`) expansion is something done by the shell [1] [2], not the program itself. The reason `~` doesn't work for `OUT_FILENAME` is that Bash sees the whole `--doc_out=...` as one word, and the `~` must come at the beginning of a word for expansion to kick in.

While in theory I could try to emulate Bash's tilde expansion when reading `OUT_FILENAME`, I think it's better not to. The rules for tilde expansion are actually quite complicated as you can see at [1], and if I tried to emulate it, it would be a crude emulation at best. If the reason you want `~` is that you don't want to hardcode the username in some script/Makefile, then I suggest you use `$HOME` instead, which will work.

Regarding filename expansion (`*` et.c.) of the input files, it should work, and it's what I'm using in the [Makefile](https://github.com/estan/protoc-gen-doc/blob/master/examples/Makefile) which builds the example.

I also ran this small test, which worked fine:

```
[estan@pyret ~]$ mkdir test
[estan@pyret ~]$ cat > test/Foo.proto
message Foo {}
[estan@pyret ~]$ cat > test/Bar.proto
message Bar {}
[estan@pyret ~]$ ls test
Bar.proto  Foo.proto
[estan@pyret ~]$ protoc --doc_out=html,index.html:. test/*.proto
[estan@pyret ~]$ ls -l index.html
-rw-r--r-- 1 estan users 8622 30 mar 19.05 index.html
```

What is happening when you try to use `*`?

[1] https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html
[2] https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html

**Comment by guozheng** [comment] 2016-03-31 05:04
just tried, it seems that I had a typo in the output dir name, so it gave path not found error. I also tried *.proto and it worked as well. Guess you must have done some magic ;-)

**Comment by acisternino** [comment] 2017-02-21 15:03
Hi,

Sorry for reviving a closed issue but I'd like to ask if there's any chance of seeing this fixed.

Currently it is impossible to use this plugin from Gradle using Google's [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) because the Gradle plugin automatically adds several `--proto_path` options to the `protoc` command line.

The error happens even if no `import` statements are used in the `.proto` files. Simply adding the `--proto_path` option triggers the bug.

Seen with protoc v3.2.0.

**Comment by estan** [comment] 2017-02-26 09:42
@acisternino It's unfortunately impossible to fix this and maintain compatibility with protobuf 2, short of reimplementing large parts of the protoc compiler import machinery. This is because there's (surprisingly) no way for a plugin to get the full on-disk path of the `.proto` file from which a `FileDescriptor` came from (see my thread at https://groups.google.com/forum/#!topic/protobuf/KxbvItIKz1k). The code that re-opens the `.proto` file to parse the beginning-of-file comment must thus make assumptions about where it is stored, and gets it wrong if it's in one of the `-I` paths :(

To fully fix this, the tool must be updated to protobuf 3, in which there is a supported way to get the beginning-of-file comment (see my bug at https://github.com/google/protobuf/issues/1385). Then the re-opening of `.proto` files to do custom parsing could be avoided altogether. But that is a part of solving #17 (adding support for protobuf 3), which I'm currently seeking help with.

So, I'm sorry to say, this won't be fixed until someone steps up to do the big work with updating the tool for protobuf 3. This issue should thus be considered part of #17.

**Closed by estan** 2017-02-26 09:42 UTC
Labels: bug
