### ISSUE TITLE
does not capture comments or default values

### ISSUE THREAD

**Issue by priyatam** [estan/protoc-gen-doc#8] opened 2015-09-09 17:12 UTC
Protobuf comments use double forward slash like [this](https://developers.google.com/protocol-buffers/docs/proto?hl=en), not "triple" forward slash as expected by the current protoc-gen-doc. As a result none of my comments are being generated in "description" fields. In addition, default values are also ignored.

**Comment by estan** [comment] 2015-09-09 17:39
This is not a bug. The use of triple slashes (or `/** ... */`, notice the double stars) is to allow protoc-gen-doc to distinguish documentation comments from normal comments. It's the same in other documentation tools like Doxygen and JavaDoc.

To mark a comment as a documentation comment (as opposed to just a regular comment), you must use `/// ...` or `/** ... */`.

**Comment by estan** [comment] 2015-09-09 17:43
Regarding default values: No, the tool does not currently capture default field values and present them in the generated documentation. That is a good feature request, but it would be great if you could file that as a separate issue.

**Comment by priyatam** [comment] 2015-09-09 18:25
Do you expect a developer to update a 10000-line codebase to fit your tool?

**Comment by estan** [comment] 2015-09-09 18:55
I'm sorry, but nearly every code documentation tool use some piece of special syntax to set off documentation comments from regular comments. How would you otherwise expect the tool to distinguish documentation comments from regular comments?

Examples include:

 * [Doxygen](http://www.stack.nl/~dimitri/doxygen/) (uses `/// ...` and `/** ...*/`)
 * [JavaDoc](https://en.wikipedia.org/wiki/Doxygen) (uses `/// ...` and `/** ...*/`)
 * [QDoc](http://doc.qt.io/qt-5/qdoc-index.html) (uses `/*! ... */`)

In fact I don't know of any code documentation tool which just blindly interprets comments in the host language as documentation comments.

So yes, I expect users of this tool to learn its syntax, just like most code documentation tools. That is part of writing the documentation: Deciding what should be documented and what should.

I'm closing this issue now, as it's definitely not a bug, but a common practice. But please open a separate issue for your feature request on default values. That is something which makes sense.

**Closed by estan** 2015-09-09 18:55 UTC
